---
- name: Add a user
  hosts: all
  tasks:
    - name: Ensure user Ansible is present
      win_user:
        name: ansible
        password: ans1bl3@P4ssw0rd
        state: present
        groups:
          - Users

    - name: Add a local and domain user to a local group
      win_group_membership:
        name: Remote Desktop Users
        members:
          - ansible
        state: present
