---
- name: installIISServer
  hosts: all
  tasks:
    - name: Install IIS Web-Server with sub features and management tools
      win_feature:
        name: "Web-Server"
        state: present
 #       restart: true
        include_sub_features: no
        include_management_tools: no
      register: iis_feature_result

    - name: Reboot System, if IIS Web-Server installation requires it
      win_reboot:
        shutdown_timeout_sec: 1200
        reboot_timeout_sec: 1200
      when: iis_feature_result.reboot_required
